[package]
identifier = "{{ identifier }}"
version = "0.1.0"
type = "lib"

[runtime]
version = "0.1.0"

[build]
input = "./dist" # Your guest code build output, the files you want to package
entrypoint = "lib.wasm" # The path to your wasm binary relative to the "input" directory
wit = "lib.wit" # The path to your libary's wit definition relative to the "input" directory
